---
title: "03_combine_cartridges"
author: "Edyta Kowalczyk"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(Seurat)
library(dplyr)
library(dbplyr)
library(dittoSeq)
library(ggplot2)
library(stringr)
library(tibble)
```

# 1. Annotate sample tag names (per cartridge)
```{r}
y2_annotated$sample <- "young2"
y3_annotated$sample <- "young3"
y4_annotated$sample <- "young4"
y5_annotated$sample <- "young5"
y6_annotated$sample <-  "young6"

#based on manifest file form customer
new_names_run8 = c("SampleTag03"="old4_CD34",
                   "SampleTag04"="old4_CD34CD38",
                   "SampleTag05"="old18_CD34",
                   "SampleTag06"="old18_CD34CD38")

new_names_run9 = c("SampleTag07"="old12_CD34",
                   "SampleTag08"="old12_CD34CD38",
                   "SampleTag09"="old19_CD34",
                   "SampleTag10"="old19_CD34CD38")

new_names_1001 = c("SampleTag09"="midage2_cd34",
                   "SampleTag10"="midage2",
                   "SampleTag11"="midage14_cd34",
                   "SampleTag12"="midage14")

new_names_1002 = c("SampleTag01"="midage8_cd34",
                   "SampleTag02"="midage8",
                   "SampleTag03"="midage11_cd34",
                   "SampleTag04"="midage11")

new_names_1003 = c("SampleTag05"="midage10_cd34",
                   "SampleTag06"="midage10",
                   "SampleTag07"="midage15_cd34",
                   "SampleTag08"="midage15")

C1001_annotated$sample <- str_replace_all(C1001_annotated$Sample_Tag, new_names_1001)

C1002_annotated$sample <- str_replace_all(C1002_annotated$Sample_Tag, new_names_1002)

C1003_annotated$sample <- str_replace_all(C1003_annotated$Sample_Tag, new_names_1003)

run8_annotated$sample <- str_replace_all(run8_annotated$Sample_Tag, new_names_run8)

run9_annotated$sample <- str_replace_all(run9_annotated$Sample_Tag, new_names_run9)
```

# 2. Annotate cell indexes with sample names
```{r}
#Create vector of cell index numbers with prefix separated by underscore
ix_run8 <- paste(run8_annotated$sample, colnames(run8_annotated), sep = "_")
ix_run9 <- paste(run9_annotated$sample, colnames(run9_annotated), sep = "_")

ix_1001 <- paste(C1001_annotated$sample, colnames(C1001_annotated), sep = "_")
ix_1002 <- paste(C1002_annotated$sample, colnames(C1002_annotated), sep = "_")
ix_1003 <- paste(C1003_annotated$sample, colnames(C1003_annotated), sep = "_")

ix_y2 <- paste(y2_annotated$sample, colnames(y2_annotated), sep = "_")
ix_y3 <- paste(y3_annotated$sample, colnames(y3_annotated), sep = "_")
ix_y4 <- paste(y4_annotated$sample, colnames(y4_annotated), sep = "_")
ix_y5 <- paste(y5_annotated$sample, colnames(y5_annotated), sep = "_")
ix_y6 <- paste(y6_annotated$sample, colnames(y6_annotated), sep = "_")

#Rename cells
run8_annotated_ix <- RenameCells(run8_annotated, new.names = ix_run8)
run9_annotated_ix <- RenameCells(run9_annotated, new.names = ix_run9)

C1001_annotated_ix <- RenameCells(C1001_annotated, new.names = ix_1001)
C1002_annotated_ix <- RenameCells(C1002_annotated, new.names = ix_1002)
C1003_annotated_ix <- RenameCells(C1003_annotated, new.names = ix_1003)

y2_annotated_ix <- RenameCells(y2_annotated, new.names = ix_y2)
y3_annotated_ix <- RenameCells(y3_annotated, new.names = ix_y3)
y4_annotated_ix <- RenameCells(y4_annotated, new.names = ix_y4)
y5_annotated_ix <- RenameCells(y5_annotated, new.names = ix_y5)
y6_annotated_ix <- RenameCells(y6_annotated, new.names = ix_y6)
```

# 3. Merge objects 
```{r}
combined_cartridges_annotated <- merge(C1001_annotated_ix, 
                             y = c(C1002_annotated_ix, 
                                   C1003_annotated_ix, 
                                   run8_annotated_ix, 
                                   run9_annotated_ix, 
                                   y2_annotated_ix, 
                                   y3_annotated_ix, 
                                   y4_annotated_ix,
                                   y5_annotated_ix, 
                                   y6_annotated_ix))
```

# 4. Exclude non-common AbSeqs
```{r}
DefaultAssay(combined_cartridges_annotated) <- "Abseq_RSEC"

counts <- GetAssayData(combined_cartridges_annotated, assay = "Abseq_RSEC")

counts <- counts[-(which(rownames(counts) %in% c('MIC-A-AB','CD44-AB.1','CD122-Nectin2-AB','CD64-AB', 'CD44-AB'))),]

clear_combined_cartridges_annotated <- subset(combined_cartridges_annotated, features = rownames(counts))

DefaultAssay(combined_cartridges_annotated) <- "RNA"

clear_combined_cartridges_annotated[["RNA"]] <- combined_cartridges_annotated@assays$RNA
```

# 5. Save cartridge & sample annotated object
```{r}
saveRDS(clear_combined_cartridges_annotated, './rds_files/combined/CCA_mrna_combined_cartridges_annotated.rds')
```

# Appendix: Create sorting labels
```{r}
sorting_labels <- c("midage10_hs" = "CD34CD38",
                    "midage11_hs" = "CD34CD38",
                    "midage14_hs" = "CD34CD38",
                    "midage15_hs" = "CD34CD38",
                    "midage2_hs" ="CD34CD38",
                    "midage8_hs" ="CD34CD38",
                    "old12_CD34CD38_hs" ="CD34CD38",
                    "old18_CD34CD38_hs"="CD34CD38",
                    "old19_CD34CD38_hs"="CD34CD38",
                    "old4_CD34CD38_hs"="CD34CD38",
                    "midage10_cd34_hs" = "CD34",
                    "midage11_cd34_hs" = "CD34",
                    "midage14_cd34_hs" = "CD34",
                    "midage15_cd34_hs" = "CD34",
                    "midage2_cd34_hs" = "CD34",
                    "midage8_cd34_hs" = "CD34",
                    "young2" = "CD34",
                    "young3" ="CD34",
                    "young4" ="CD34",
                    "young5" ="CD34",
                    "young6" ="CD34",
                    "old12_CD34_hs" ="CD34",
                    "old18_CD34_hs" ="CD34",
                    "old19_CD34_hs" ="CD34",
                    "old4_CD34_hs" ="CD34"
                    )

clear_combined_cartridges_annotated$sorting <- str_replace_all(clear_combined_cartridges_annotated$sample, sorting_labels)
```