---
title: "03_combine_cartridges"
author: "Edyta Kowalczyk"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(Seurat)
library(dplyr)
library(dbplyr)
library(dittoSeq)
library(ggplot2)
library(stringr)
library(tibble)
```

# 1. Annotate sample tag names (per cartridge)
```{r}


Exp_1_annotated$sample <- "young2"
Exp_2_annotated$sample <- "young3"
Exp_3_annotated$sample <- "young3"
Exp_4_annotated$sample <- "young4"
Exp_5_annotated$sample <- "young5"


new_names_exp_6 = c("SampleTag03"="old4_CD34",
                   "SampleTag04"="old4_CD34CD38",
                   "SampleTag05"="old18_CD34",
                   "SampleTag06"="old18_CD34CD38")

new_names_exp_7 = c("SampleTag07"="old12_CD34",
                   "SampleTag08"="old12_CD34CD38",
                   "SampleTag09"="old19_CD34",
                   "SampleTag10"="old19_CD34CD38")

new_names_exp_8 = c("SampleTag09"="midage2_CD34",
                   "SampleTag10"="midage2_CD34CD38",
                   "SampleTag11"="midage14_CD34",
                   "SampleTag12"="midage14_CD34CD38")

new_names_exp_9 = c("SampleTag01"="midage8_CD34",
                   "SampleTag02"="midage8_CD34CD38",
                   "SampleTag03"="midage11_CD34",
                   "SampleTag04"="midage11_CD34CD38")

new_names_exp_10 = c("SampleTag05"="midage10_CD34",
                   "SampleTag06"="midage10_CD34CD38",
                   "SampleTag07"="midage15_CD34",
                   "SampleTag08"="midage15_CD34CD38")


Exp_6_annotated$sample <- str_replace_all(Exp_6_annotated$Sample_Tag, new_names_exp_6)

Exp_7_annotated$sample <- str_replace_all(Exp_7_annotated$Sample_Tag, new_names_exp_7)

Exp_8_annotated$sample <- str_replace_all(Exp_8_annotated$Sample_Tag, new_names_exp_8)

Exp_9_annotated$sample <- str_replace_all(Exp_9_annotated$Sample_Tag, new_names_exp_9)

Exp_10_annotated$sample <- str_replace_all(Exp_10_annotated$Sample_Tag, new_names_exp_10)


```

# 2. Annotate cell indexes with sample names
```{r}
#Create vector of cell index numbers with prefix separated by underscore


ix_Exp_1 <- paste(Exp_1_annotated$sample, colnames(Exp_1_annotated), sep = "_")
ix_Exp_2 <- paste(Exp_2_annotated$sample, colnames(Exp_2_annotated), sep = "_")
ix_Exp_3 <- paste(Exp_3_annotated$sample, colnames(Exp_3_annotated), sep = "_")
ix_Exp_4 <- paste(Exp_4_annotated$sample, colnames(Exp_4_annotated), sep = "_")
ix_Exp_5 <- paste(Exp_5_annotated$sample, colnames(Exp_5_annotated), sep = "_")


ix_Exp_6 <- paste(Exp_6_annotated$sample, colnames(Exp_6_annotated), sep = "_")
ix_Exp_7 <- paste(Exp_7_annotated$sample, colnames(Exp_7_annotated), sep = "_")

ix_Exp_8 <- paste(Exp_8_annotated$sample, colnames(Exp_8_annotated), sep = "_")
ix_Exp_9 <- paste(Exp_9_annotated$sample, colnames(Exp_9_annotated), sep = "_")
ix_Exp_10 <- paste(Exp_10_annotated$sample, colnames(Exp_10_annotated), sep = "_")


#Rename cells

Exp_1_annotated_ix  <- RenameCells(Exp_1_annotated, new.names = ix_Exp_1)
Exp_2_annotated_ix  <- RenameCells(Exp_2_annotated, new.names = ix_Exp_2)
Exp_3_annotated_ix  <- RenameCells(Exp_3_annotated, new.names = ix_Exp_3)
Exp_4_annotated_ix  <- RenameCells(Exp_4_annotated, new.names = ix_Exp_4)
Exp_5_annotated_ix  <- RenameCells(Exp_5_annotated, new.names = ix_Exp_5)

Exp_6_annotated_ix  <- RenameCells(Exp_6_annotated, new.names = ix_Exp_6)
Exp_7_annotated_ix  <- RenameCells(Exp_7_annotated, new.names = ix_Exp_7)

Exp_8_annotated_ix  <- RenameCells(Exp_8_annotated, new.names = ix_Exp_8)
Exp_9_annotated_ix  <- RenameCells(Exp_9_annotated, new.names = ix_Exp_9)
Exp_10_annotated_ix  <- RenameCells(Exp_10_annotated, new.names = ix_Exp_10)

```

# 3. Merge objects 
```{r}
combined_cartridges_annotated <- merge(Exp_1_annotated_ix, 
                             y = c(Exp_2_annotated_ix, 
                                  Exp_3_annotated_ix, 
                                  Exp_4_annotated_ix, 
                                  Exp_5_annotated_ix, 
                                  Exp_6_annotated_ix, 
                                  Exp_7_annotated_ix, 
                                  Exp_8_annotated_ix,
                                  Exp_9_annotated_ix, 
                                  Exp_10_annotated_ix))
```

# 4. Exclude non-common AbSeqs
```{r}
DefaultAssay(combined_cartridges_annotated) <- "Abseq_RSEC"

counts <- GetAssayData(combined_cartridges_annotated, assay = "Abseq_RSEC")

counts <- counts[-(which(rownames(counts) %in% c('MIC-A-AB','CD44-AB.1','CD122-Nectin2-AB','CD64-AB', 'CD44-AB'))),]

clear_combined_cartridges_annotated <- subset(combined_cartridges_annotated, features = rownames(counts))

DefaultAssay(combined_cartridges_annotated) <- "RNA"

clear_combined_cartridges_annotated[["RNA"]] <- combined_cartridges_annotated@assays$RNA
```

# 5. Save cartridge & sample annotated object
```{r}
saveRDS(clear_combined_cartridges_annotated, './rds_files/combined/CCA_mrna_combined_cartridges_annotated.rds')
```

# Appendix: Create sorting labels
```{r}
sorting_labels <- c("midage10_hs" = "CD34CD38",
                    "midage11_hs" = "CD34CD38",
                    "midage14_hs" = "CD34CD38",
                    "midage15_hs" = "CD34CD38",
                    "midage2_hs" ="CD34CD38",
                    "midage8_hs" ="CD34CD38",
                    "old12_CD34CD38_hs" ="CD34CD38",
                    "old18_CD34CD38_hs"="CD34CD38",
                    "old19_CD34CD38_hs"="CD34CD38",
                    "old4_CD34CD38_hs"="CD34CD38",
                    "midage10_cd34_hs" = "CD34",
                    "midage11_cd34_hs" = "CD34",
                    "midage14_cd34_hs" = "CD34",
                    "midage15_cd34_hs" = "CD34",
                    "midage2_cd34_hs" = "CD34",
                    "midage8_cd34_hs" = "CD34",
                    "young2" = "CD34",
                    "young3" ="CD34",
                    "young4" ="CD34",
                    "young5" ="CD34",
                    "young6" ="CD34",
                    "old12_CD34_hs" ="CD34",
                    "old18_CD34_hs" ="CD34",
                    "old19_CD34_hs" ="CD34",
                    "old4_CD34_hs" ="CD34"
                    )

clear_combined_cartridges_annotated$sorting <- str_replace_all(clear_combined_cartridges_annotated$sample, sorting_labels)
```
